import { Inter } from 'next/font/google'
// import '../../../globals.css'
import Navbar from '../../../components/admin/Navbar'
import LeftMenu from '../../../components/admin/LeftMenu'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function Layout({ children }) {
    return (
        <>
            <Navbar />
            <div className='flex w-full'>
                <LeftMenu />
                {children}
            </div>
        </>

    )
}
